# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
name: Patrick Huber
profile:
  image: banner.png
  title: <h4><span style='font-weight:700'>Patrick</span> <span style='font-weight:100'>Huber</span></h4>
  email: huberpat@cs.ubc.ca
  affiliation: University of British Columbia
  description:
            <h6 style='font-weight:600; font-family:"Spartan";'>Welcome to my Website!</h6>
            <p style='font-weight:400; margin-top:10px'>I am a third year <a href='https://www.grad.ubc.ca/campus-community/meet-our-students/huber-patrick' target="_blank">Ph.D. candidate</a> in the <a href='http://www.cs.ubc.ca/cs-research/lci/research-groups/natural-language-processing/' target="_blank">NLP Lab</a> at the <a href='https://www.ubc.ca/' target="_blank">University of British Columbia.</a></p>
            <p style='font-weight:400; margin-top:10px'>I am interested in innovative applications of machine learning methods and algorithms, focusing on designing and implementing computational models that enable automated systems to better understand natural language.</p>
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://www.cs.ubc.ca/~huberpat/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: huberpa
github_username:  huberpa
include: ['_pages']

scholar:
  locale: en
  bibliography_template: "bib"
  use_raw_bibtex_entry: true
  sort_by: none
  order: ascending
  group_by: none
  group_order: ascending
  bibliography_list_tag: ul

collections:
  news:
    defaults:
      layout: post
    output: true
    permalink: /news/:path/
  talks:
    defaults:
      layout: post
    output: true
    permalink: /talks/:path/
  reviews:
    defaults:
      layout: post
    output: true
    permalink: /reviews/:path/
  awards:
    defaults:
      layout: post
    output: true
    permalink: /awards/:path/

# Build settings
markdown: kramdown
theme:
plugins:
  - jekyll-feed
  - jekyll-scholar
  - jekyll-seo-tag


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
